# arguments for dataset
dataset: vaihingen
nclass: 6
crop_size: 400
data_root: /home/dgyu/public/workspace/LSST-master/data/vaihingen

# arguments for training
epochs: 200
batch_size: 4 # per GPU x 4 GPUs
lr: 0.005
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
conf_thresh: 0.9




# arguments for model
backbone: resnet101
replace_stride_with_dilation: [False, True, True]
dilations: [6, 12, 18]
